window.data = {
    "games": [
        {
            "id": "game0",
            "name": "Strategy Game for PC",
            "isSale": true,
            "isBundle": false,
            "price": 30,
            "discount": 50,
            "discountTime": "2025-06-05T23:59:59",
            "genre": "Strategy",
            "platform": "PC",
            "wishlist": true,
            "bestSelling": true,
            "rating": 4.5,
            "images": ["images/strategy01.jpg", "images/strategy02.jpg"],
            "description": "A turn-based strategy game set in medieval times.",
            "systemRequirements": "Windows 10, i5 CPU, 8GB RAM, GTX 1060",
            "timer": true,
            "communityReview": "Very engaging with challenging mechanics.",
            "userReviews": [
                {"user": "User1", "stars": 5, "text": "Awesome game!"},
                {"user": "User2", "stars": 4, "text": "Good mechanics."}
            ],
            "steamReview": 92,
            "isNew": true
        },
        {
            "id": "game1",
            "name": "Puzzle Adventure Game for Switch",
            "isSale": true,
            "isBundle": false,
            "price": 25,
            "discount": 30,
            "discountTime": "2025-06-05T09:21:19.278870",
            "genre": "Puzzle",
            "platform": "Switch",
            "wishlist": false,
            "bestSelling": false,
            "rating": 4.2,
            "images": ["images/puzzle.jpg", "images/puzzle02.jpg"],
            "description": "Solve intricate puzzles across an enchanting world.",
            "systemRequirements": "Nintendo Switch Console",
            "timer": true,
            "communityReview": "Challenging and fun for all ages.",
            "userReviews": [
                {"user": "PuzzleLover", "stars": 5, "text": "Absolutely brilliant puzzles."},
                {"user": "Thinker82", "stars": 4, "text": "Great game with some tricky moments."}
            ],
            "steamReview": 88,
            "isNew": true
        },
        {
            "id": "game2",
            "name": "Sci-Fi RPG Game for Xbox",
            "isSale": false,
            "isBundle": false,
            "price": 35,
            "discount": 0,
            "discountTime": null,
            "genre": "RPG",
            "platform": "Xbox",
            "wishlist": true,
            "bestSelling": true,
            "rating": 4.7,
            "images": ["images/RPG.jpg", "images/witcher3.jpg"],
            "description": "Explore galaxies and make choices that shape your destiny.",
            "systemRequirements": "Xbox Series X/S",
            "timer": false,
            "communityReview": "Immersive and visually stunning.",
            "userReviews": [
                {"user": "SciFiFan99", "stars": 5, "text": "Incredible story and visuals!"},
                {"user": "RPGMaster", "stars": 4, "text": "Loved the branching storylines."}
            ],
            "steamReview": 91,
            "isNew": false
        },
        {
            "id": "game3",
            "name": "Casual Puzzle Game for Mobile",
            "isSale": true,
            "isBundle": false,
            "price": 10,
            "discount": 20,
            "discountTime": "2025-06-04T09:26:11.461536",
            "genre": "Puzzle",
            "platform": "Mobile",
            "wishlist": false,
            "bestSelling": false,
            "rating": 3.8,
            "images": ["images/mobilpuzzle.jpg", "images/mobilepuzzle02.jpg"],
            "description": "Relaxing mobile game with colorful puzzles and daily challenges.",
            "systemRequirements": "iOS/Android, 2GB RAM",
            "timer": true,
            "communityReview": "Fun to play during breaks.",
            "userReviews": [
                {"user": "CasualGamer", "stars": 4, "text": "Perfect for killing time!"},
                {"user": "PuzzleFan", "stars": 3, "text": "Wish there were more levels."}
            ],
            "steamReview": 76,
            "isNew": true
        },
        {
            "id": "game4",
            "name": "Educational Simulation Game for Web",
            "isSale": false,
            "isBundle": false,
            "price": 15,
            "discount": 0,
            "discountTime": null,
            "genre": "Simulation",
            "platform": "Web",
            "wishlist": true,
            "bestSelling": false,
            "rating": 4.0,
            "images": ["images/simulation.jpg", "images/simulation02.jpg"],
            "description": "Learn economics and resource management through this interactive simulation game.",
            "systemRequirements": "Modern web browser, 4GB RAM",
            "timer": false,
            "communityReview": "A smart way to learn while playing.",
            "userReviews": [
                {"user": "TeacherX", "stars": 4, "text": "Great for students!"},
                {"user": "SimFan", "stars": 4, "text": "Well designed and educational."}
            ],
            "steamReview": 84,
            "isNew": true
        },
        {
            "id": "game5",
            "name": "Rhythm Music Game for PS",
            "isSale": true,
            "isBundle": false,
            "price": 20,
            "discount": 25,
            "discountTime": "2025-06-06T09:28:50.949012",
            "genre": "Rhythm",
            "platform": "PS",
            "wishlist": false,
            "bestSelling": true,
            "rating": 4.6,
            "images": ["images/rhythm01.jpg", "images/rhythm02.jpg"],
            "description": "Tap to the beat and master over 100 music tracks in this energetic rhythm game.",
            "systemRequirements": "PlayStation 4/5",
            "timer": true,
            "communityReview": "Addictive gameplay with an amazing soundtrack.",
            "userReviews": [
                {"user": "BeatMaster", "stars": 5, "text": "Music and gameplay are top-notch!"},
                {"user": "DanceFan22", "stars": 4, "text": "Very fun, some hard levels."}
            ],
            "steamReview": 89,
            "isNew": false
        },
        {
            "id": "game6",
            "name": "Local Co-op Party Game for PC",
            "isSale": false,
            "isBundle": false,
            "price": 18,
            "discount": 0,
            "discountTime": null,
            "genre": "Party",
            "platform": "PC",
            "wishlist": true,
            "bestSelling": false,
            "rating": 4.1,
            "images": ["images/coopparty01.jpg", "images/coopparty02.jpg"],
            "description": "Gather your friends for mini-game chaos in this hilarious party title.",
            "systemRequirements": "Windows 10, 4GB RAM, integrated graphics",
            "timer": false,
            "communityReview": "Great for game nights with friends!",
            "userReviews": [
                {"user": "PartyPlayer", "stars": 4, "text": "Laughs guaranteed."},
                {"user": "FriendZone", "stars": 4, "text": "Needs more minigames but fun!"}
            ],
            "steamReview": 83,
            "isNew": true
        },
        {
            "id": "game7",
            "name": "Horror Survival Game for PS",
            "isSale": true,
            "isBundle": false,
            "price": 40,
            "discount": 40,
            "discountTime": "2025-06-08T12:00:00",
            "genre": "Horror",
            "platform": "PS",
            "wishlist": false,
            "bestSelling": true,
            "rating": 4.9,
            "images": ["images/horror.jpg", "images/horror02.jpg"],
            "description": "Survive the night in a haunted mansion filled with terrifying creatures.",
            "systemRequirements": "PlayStation 4/5, 8GB RAM",
            "timer": true,
            "communityReview": "Terrifying atmosphere and great story.",
            "userReviews": [
                {"user": "ScaryCat", "stars": 5, "text": "Best horror game I've played!"},
                {"user": "NightOwl", "stars": 4, "text": "Creepy and immersive."}
            ],
            "steamReview": 95,
            "isNew": false
        },
        {
            "id": "game8",
            "name": "Fantasy Action Game for Xbox",
            "isSale": true,
            "isBundle": false,
            "price": 50,
            "discount": 20,
            "discountTime": "2025-06-09T15:30:00",
            "genre": "Action",
            "platform": "Xbox",
            "wishlist": true,
            "bestSelling": true,
            "rating": 4.8,
            "images": ["images/fantasy01.jpg", "images/fantasy02.jpg"],
            "description": "Embark on an epic quest in a magical world filled with mythical creatures.",
            "systemRequirements": "Xbox Series X/S, 12GB RAM",
            "timer": true,
            "communityReview": "Epic battles and stunning graphics.",
            "userReviews": [
                {"user": "EpicGamer", "stars": 5, "text": "Loved the combat system!"},
                {"user": "QuestLover", "stars": 4, "text": "Great story and characters."}
            ],
            "steamReview": 90,
            "isNew": false
        },
        {
            "id": "game9",
            "name": "Indie Platformer for PC",
            "isSale": false,
            "isBundle": false,
            "price": 15,
            "discount": 0,
            "discountTime": null,
            "genre": "Platformer",
            "platform": "PC",
            "wishlist": true,
            "bestSelling": false,
            "rating": 4.3,
            "images": ["images/platformer.jpg", "images/platformer02.jpg"],
            "description": "A charming indie platformer with hand-drawn art and challenging levels.",
            "systemRequirements": "Windows 10, 4GB RAM, integrated graphics",
            "timer": false,
            "communityReview": "Beautiful art style and fun gameplay.",
            "userReviews": [
                {"user": "ArtLover", "stars": 5, "text": "Stunning visuals!"},
                {"user": "PlatformerFan", "stars": 4, "text": "Challenging but rewarding."}
            ],
            "steamReview": 87,
            "isNew": true
        },
        {
            "id": "game10",
            "name": "Multiplayer Shooter for PS",
            "isSale": true,
            "isBundle": false,
            "price": 45,
            "discount": 30,
            "discountTime": "2025-06-10T18:00:00",
            "genre": "Shooter",
            "platform": "PS",
            "wishlist": false,
            "bestSelling": true,
            "rating": 4.4,
            "images": ["images/multiplayer01.jpg", "images/multiplayer02.jpg"],
            "description": "Join the battle in this fast-paced multiplayer shooter with various game modes.",
            "systemRequirements": "PlayStation 4/5, 8GB RAM",
            "timer": true,
            "communityReview": "Intense and addictive gameplay.",
            "userReviews": [
                {"user": "ShooterFan", "stars": 5, "text": "Best shooter I've played!"},
                {"user": "TeamPlayer", "stars": 4, "text": "Great teamwork mechanics."}
            ],
            "steamReview": 91,
            "isNew": false
        },
        {
            "id": "game20",
            "name": "Empire Tactics",
            "genre": "Strategy",
            "platform": "PC",
            "price": 30,
            "discount": 15,
            "discountTime": "2025-06-10T23:59:59",
            "isSale": true,
            "isBundle": false,
            "wishlist": false,
            "bestSelling": false,
            "rating": 4.2,
            "images": ["images/empire_tactics.jpg"],
            "description": "Rule vast lands with your brilliant strategies.",
            "systemRequirements": "Windows 10, 4GB RAM",
            "timer": true,
            "communityReview": "Classic top-down strategy.",
            "userReviews": [],
            "steamReview": 85,
            "isNew": true
          },
          {
            "id": "game21",
            "name": "Tactical Conquest",
            "genre": "Strategy",
            "platform": "PC",
            "price": 27,
            "discount": 0,
            "discountTime": null,
            "isSale": false,
            "isBundle": false,
            "wishlist": true,
            "bestSelling": false,
            "rating": 4.0,
            "images": ["images/tactical_conquest.jpg"],
            "description": "Turn-based strategy focused on resource control.",
            "systemRequirements": "Windows 10, 6GB RAM",
            "timer": false,
            "communityReview": "Well-balanced and competitive.",
            "userReviews": [],
            "steamReview": 80,
            "isNew": true
          },
          {
            "id": "game22",
            "name": "World War Sim",
            "genre": "Strategy",
            "platform": "PC",
            "price": 35,
            "discount": 10,
            "discountTime": "2025-06-09T23:59:59",
            "isSale": true,
            "isBundle": false,
            "wishlist": false,
            "bestSelling": true,
            "rating": 4.6,
            "images": ["images/world_war_sim.jpg"],
            "description": "Command entire armies in a realistic war simulation.",
            "systemRequirements": "Windows 10, 8GB RAM",
            "timer": true,
            "communityReview": "Massive and realistic warfare.",
            "userReviews": [],
            "steamReview": 90,
            "isNew": false
          },
          {
            "id": "game23",
            "name": "Siege Commander",
            "genre": "Strategy",
            "platform": "PC",
            "price": 22,
            "discount": 20,
            "discountTime": "2025-06-12T12:00:00",
            "isSale": true,
            "isBundle": false,
            "wishlist": true,
            "bestSelling": false,
            "rating": 4.1,
            "images": ["images/siege_commander.jpg"],
            "description": "Lead medieval sieges and defend your kingdom.",
            "systemRequirements": "Windows 10, 6GB RAM",
            "timer": true,
            "communityReview": "Challenging and rewarding battles.",
            "userReviews": [],
            "steamReview": 84,
            "isNew": true
          },
          {
            "id": "game24",
            "name": "Galaxy Front",
            "genre": "Strategy",
            "platform": "PC",
            "price": 29,
            "discount": 0,
            "discountTime": null,
            "isSale": false,
            "isBundle": false,
            "wishlist": false,
            "bestSelling": false,
            "rating": 4.4,
            "images": ["images/galaxy_front.jpg"],
            "description": "Dominate alien star systems through diplomacy and war.",
            "systemRequirements": "Windows 10, 8GB RAM",
            "timer": false,
            "communityReview": "Deep space politics and war.",
            "userReviews": [],
            "steamReview": 88,
            "isNew": true
          },
          {
            "id": "game25",
            "name": "Urban Strategist",
            "genre": "Strategy",
            "platform": "PC",
            "price": 18,
            "discount": 10,
            "discountTime": "2025-06-08T12:00:00",
            "isSale": true,
            "isBundle": false,
            "wishlist": true,
            "bestSelling": false,
            "rating": 4.0,
            "images": ["images/urban_strategist.jpg"],
            "description": "Plan, build, and rule the city of the future.",
            "systemRequirements": "Windows 10, 4GB RAM",
            "timer": true,
            "communityReview": "Very creative sandbox.",
            "userReviews": [],
            "steamReview": 82,
            "isNew": true
          },
          {
            "id": "game30",
            "name": "Nightmare Asylum",
            "genre": "Horror",
            "platform": "PS",
            "price": 35,
            "discount": 20,
            "discountTime": "2025-06-11T23:59:59",
            "isSale": true,
            "isBundle": false,
            "wishlist": true,
            "bestSelling": true,
            "rating": 4.7,
            "images": ["images/nightmare_asylum.jpg"],
            "description": "Explore an abandoned asylum haunted by unspeakable horrors.",
            "systemRequirements": "PlayStation 4/5, 8GB RAM",
            "timer": true,
            "communityReview": "Terrifying visuals and amazing sound design.",
            "userReviews": [],
            "steamReview": 91,
            "isNew": false
          },
          {
            "id": "game31",
            "name": "Whispers in the Dark",
            "genre": "Horror",
            "platform": "PS",
            "price": 28,
            "discount": 15,
            "discountTime": "2025-06-09T18:00:00",
            "isSale": true,
            "isBundle": false,
            "wishlist": false,
            "bestSelling": false,
            "rating": 4.2,
            "images": ["images/whispers_dark.jpg"],
            "description": "Use sound to navigate pitch-black halls full of ghosts.",
            "systemRequirements": "PlayStation 4/5, 8GB RAM",
            "timer": true,
            "communityReview": "Psychological thriller at its best.",
            "userReviews": [],
            "steamReview": 86,
            "isNew": true
          },
          {
            "id": "game32",
            "name": "The Forgotten Cellar",
            "genre": "Horror",
            "platform": "PS",
            "price": 25,
            "discount": 0,
            "discountTime": null,
            "isSale": false,
            "isBundle": false,
            "wishlist": true,
            "bestSelling": false,
            "rating": 4.0,
            "images": ["images/forgotten_cellar.jpg"],
            "description": "You inherit a house… and something else deep beneath it.",
            "systemRequirements": "PlayStation 4/5",
            "timer": false,
            "communityReview": "Claustrophobic and atmospheric.",
            "userReviews": [],
            "steamReview": 83,
            "isNew": true
          },
          {
            "id": "game33",
            "name": "Cursed Forest",
            "genre": "Horror",
            "platform": "PS",
            "price": 30,
            "discount": 10,
            "discountTime": "2025-06-07T21:00:00",
            "isSale": true,
            "isBundle": false,
            "wishlist": false,
            "bestSelling": false,
            "rating": 4.1,
            "images": ["images/cursed_forest.jpg"],
            "description": "Escape a cursed forest while haunted by ancient spirits.",
            "systemRequirements": "PlayStation 4/5, 6GB RAM",
            "timer": true,
            "communityReview": "Creepy and beautiful.",
            "userReviews": [],
            "steamReview": 84,
            "isNew": true
          },
          {
            "id": "game34",
            "name": "Haunted Echoes",
            "genre": "Horror",
            "platform": "PS",
            "price": 33,
            "discount": 5,
            "discountTime": "2025-06-10T16:00:00",
            "isSale": true,
            "isBundle": false,
            "wishlist": true,
            "bestSelling": false,
            "rating": 4.3,
            "images": ["images/haunted_echoes.jpg"],
            "description": "A haunted radio broadcasts warnings too late to save you.",
            "systemRequirements": "PlayStation 4/5",
            "timer": true,
            "communityReview": "Unique story and cool mechanic.",
            "userReviews": [],
            "steamReview": 88,
            "isNew": true
          },
          {
            "id": "game40",
            "name": "Pixel Runner",
            "genre": "Platformer",
            "platform": "PC",
            "price": 12,
            "discount": 20,
            "discountTime": "2025-06-12T12:00:00",
            "isSale": true,
            "isBundle": false,
            "wishlist": true,
            "bestSelling": false,
            "rating": 4.2,
            "images": ["images/pixel_runner.jpg"],
            "description": "A retro-style runner with pixel-perfect controls and levels.",
            "systemRequirements": "Windows 10, 4GB RAM",
            "timer": true,
            "communityReview": "Simple and addicting.",
            "userReviews": [],
            "steamReview": 84,
            "isNew": true
          },
          {
            "id": "game41",
            "name": "Dreamscape",
            "genre": " Platformer",
            "platform": "PC",
            "price": 15,
            "discount": 0,
            "discountTime": null,
            "isSale": false,
            "isBundle": false,
            "wishlist": false,
            "bestSelling": false,
            "rating": 4.4,
            "images": ["images/dreamscape.jpg","images/empire_tactics.jpg"],
            "description": "Explore a hand-painted dream world in this atmospheric journey.",
            "systemRequirements": "Windows 10, 6GB RAM",
            "timer": false,
            "communityReview": "Relaxing with great visuals.",
            "userReviews": [],
            "steamReview": 87,
            "isNew": true
          },
          {
            "id": "game42",
            "name": "Loop Architect",
            "genre": " Platformer",
            "platform": "PC",
            "price": 10,
            "discount": 50,
            "discountTime": "2025-06-10T23:59:59",
            "isSale": true,
            "isBundle": false,
            "wishlist": true,
            "bestSelling": false,
            "rating": 4.1,
            "images": ["images/loop_architect.jpg"],
            "description": "Solve intricate puzzles by designing perfect loops.",
            "systemRequirements": "Windows 10, 4GB RAM",
            "timer": true,
            "communityReview": "Satisfying and clever.",
            "userReviews": [],
            "steamReview": 83,
            "isNew": true
          },
          {
            "id": "game43",
            "name": "Ink Blade",
            "genre": " Platformer",
            "platform": "PC",
            "price": 18,
            "discount": 10,
            "discountTime": "2025-06-13T18:00:00",
            "isSale": true,
            "isBundle": false,
            "wishlist": false,
            "bestSelling": true,
            "rating": 4.5,
            "images": ["images/ink_blade.jpg"],
            "description": "Fight through ink-drawn dungeons in this stylish action game.",
            "systemRequirements": "Windows 10, 6GB RAM",
            "timer": true,
            "communityReview": "Fluid combat and great art.",
            "userReviews": [],
            "steamReview": 89,
            "isNew": true
          },
          {
            "id": "game44",
            "name": "Bard's Quest",
            "genre": " Platformer",
            "platform": "PC",
            "price": 14,
            "discount": 0,
            "discountTime": null,
            "isSale": false,
            "isBundle": false,
            "wishlist": false,
            "bestSelling": false,
            "rating": 4.0,
            "images": ["images/bards_quest.jpg"],
            "description": "Sing your way to victory in this quirky musical RPG.",
            "systemRequirements": "Windows 10, 4GB RAM",
            "timer": false,
            "communityReview": "Funny and original.",
            "userReviews": [],
            "steamReview": 82,
            "isNew": true
          },
          {
            "id": "game45",
            "name": "Wanderlight",
            "genre": " Platformer",
            "platform": "PC",
            "price": 20,
            "discount": 30,
            "discountTime": "2025-06-15T12:00:00",
            "isSale": true,
            "isBundle": false,
            "wishlist": true,
            "bestSelling": false,
            "rating": 4.3,
            "images": ["images/wanderlight.jpg"],
            "description": "A poetic journey through a surreal world of light.",
            "systemRequirements": "Windows 10, 4GB RAM",
            "timer": true,
            "communityReview": "Beautiful and meditative.",
            "userReviews": [],
            "steamReview": 85,
            "isNew": true
          },
          {
            "id": "game50",
            "name": "Strategy Game for Mac",
            "isSale": true,
            "isBundle": false,
            "price": 30,
            "discount": 50,
            "discountTime": "2025-06-05T23:59:59",
            "genre": "Strategy",
            "platform": "Mac",
            "wishlist": true,
            "bestSelling": true,
            "rating": 4.5,
            "images": ["images/strategy01.jpg", "images/strategy02.jpg"],
            "description": "A turn-based strategy game set in medieval times.",
            "systemRequirements": "Windows 10, i5 CPU, 8GB RAM, GTX 1060",
            "timer": true,
            "communityReview": "Very engaging with challenging mechanics.",
            "userReviews": [
                {"user": "User1", "stars": 5, "text": "Awesome game!"},
                {"user": "User2", "stars": 4, "text": "Good mechanics."}
            ],
            "steamReview": 92,
            "isNew": true
        },
        {
            "id": "game51",
            "name": "FPS Game for PC",
            "isSale": true,
            "isBundle": false,
            "price": 30,
            "discount": 50,
            "discountTime": "2025-06-05T23:59:59",
            "genre": "FPS",
            "platform": "PC",
            "wishlist": true,
            "bestSelling": true,
            "rating": 4.5,
            "images": ["images/strategy01.jpg", "images/strategy02.jpg"],
            "description": "A turn-based strategy game set in medieval times.",
            "systemRequirements": "Windows 10, i5 CPU, 8GB RAM, GTX 1060",
            "timer": true,
            "communityReview": "Very engaging with challenging mechanics.",
            "userReviews": [
                {"user": "User1", "stars": 5, "text": "Awesome game!"},
                {"user": "User2", "stars": 4, "text": "Good mechanics."}
            ],
            "steamReview": 92,
            "isNew": true
        },
    ],


    "bundles": [
        {
            "id": "bundle1",
            "name": "Strategy Pack",
            "isBundle": true,
            "isSale": false, // discount > 0
            "platform": "PC",
            "wishlist": false,
            "rating": 4.8,
            "description": "A collection of strategy games for PC enthusiasts.",
            "images": ["images/strategybundle.jpg"],
            "basePrice": 30, // Use the highest tier price as the base
            "tiers": [
                { "price": 10, "gamesIncluded": ["Strategy Game for PC", "Empire Tactics"] },
                { "price": 20, "gamesIncluded": ["Strategy Game for PC", "Empire Tactics", "Tactical Conquest"] },
                { "price": 30, "gamesIncluded": ["Strategy Game for PC", "Empire Tactics", "Tactical Conquest", "Galaxy Front", "World War Sim"] }
            ],
            "discount": 0,
            "discountTime": "2025-06-07T23:59:59",
            "timer": true,
            "communityReview": "Amazing value for strategy lovers.",
            "userReviews": [
                { "user": "BundleFan1", "stars": 5, "text": "Best bundle I've bought." },
                { "user": "BudgetGamer", "stars": 4, "text": "Saved a lot." }
            ],
            "steamReview": 89,
            "isNew": false
        },
        {
            "id": "bundle2",
            "name": "Horror Collection",
            "isBundle": true,
            "isSale": true, // discount > 0
            "platform": "PS",
            "wishlist": false,
            "rating": 4.7,
            "description": "Terrifying horror games for PS players.",
            "images": ["images/horrorbundle.jpg"],
            "basePrice": 35, // Use the highest tier price as the base
            "tiers": [
                { "price": 15, "gamesIncluded": ["Horror Survival Game for PS", "Nightmare Asylum"] },
                { "price": 25, "gamesIncluded": ["Horror Survival Game for PS", "Nightmare Asylum", "Cursed Forest"] },
                { "price": 35, "gamesIncluded": ["Horror Survival Game for PS", "Nightmare Asylum", "Cursed Forest", "Haunted Echoes"] }
            ],
            "discount": 40,
            "discountTime": "2025-06-08T23:59:59",
            "timer": true,
            "communityReview": "Perfect for horror fans.",
            "userReviews": [
                { "user": "HorrorFan", "stars": 5, "text": "So creepy!" },
                { "user": "ThrillSeeker", "stars": 4, "text": "Great scares." }
            ],
            "steamReview": 92,
            "isNew": false
        },
        {
            "id": "bundle3",
            "name": "Indie Gems",
            "isBundle": true,
            "isSale": true, // discount > 0
            "platform": "PC",
            "wishlist": false,
            "rating": 4.5,
            "description": "A curated selection of indie games for PC.",
            "images": ["images/indiebundle.jpg"],
            "basePrice": 25, // Use the highest tier price as the base
            "tiers": [
                { "price": 5, "gamesIncluded": ["Bard's Quest"] },
                { "price": 15, "gamesIncluded": ["Bard's Quest", "Dreamscape", "Loop Architect"] },
                { "price": 25, "gamesIncluded": ["Bard's Quest", "Dreamscape", "Loop Architect", "Ink Blade", "Wanderlight"] }
            ],
            "discount": 60,
            "discountTime": "2025-06-09T23:59:59",
            "timer": true,
            "communityReview": "Hidden gems worth every penny.",
            "userReviews": [
                { "user": "IndieLover", "stars": 5, "text": "Amazing indie titles!" },
                { "user": "GamerX", "stars": 4, "text": "Really fun games." }
            ],
            "steamReview": 87,
            "isNew": true
        }
    ]
};